---
swagger: '2.0'

################################################################################
#                              API Information                                 #
################################################################################
info:
  version: v0.1
  title: Intersis API
  description: |

    ## Introduction

    ### What is InterSIS?

    InterSIS is an API and a set of SDKs to help software developers and school districts hold student information in a single, secure place.

    ## Authentication

    ### Client Registration

    Here's some information about client registration.

    {{see #clients}}

    ### Authentication Endpoints

    {{see #whoami}}

    ### Data

################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################
basePath: /v0.1
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json

################################################################################
#                                  Security                                    #
################################################################################
securityDefinitions:
  oauth:
    type: oauth2
    flow: implicit
    authorizationUrl: /o/authorize/?redirect_uri=CALLBACK_URI&scope=SCOPES&state=STATE&client_id=CLIENT_ID
    scopes:
      read-write: to read/modify/create any resources on a user's behalf.
      read: to read any resources on a user's behalf.
      read-rostering: |
        to read the the user's course names, course descriptions, and section rosters,
        not including student names or demographic information.
      read-student-names: read any student names or profile names on the user's behalf
      read-student-profile-names: read any student names on the user's behalf
      read-client: read user details about the client
  key:
    type: apiKey
    in: query
    name: access_token
security:
  - oauth:
    - read-write
    - read
    - read-rostering
    - read-student-names
    - read-student-profile-names
    - read-client
  - key: []

################################################################################
#                                   Parameters                                 #
################################################################################

parameters:
#                                   Path Parameters                            #
  path:
    userId:
      name: user_id
      in: path
      description: User resource identification string
      required: true
      type: string
#                                   Clients                                #
  clients:
    redirect_uris:
      required:
        in: formData
        name: redirect_uris
        description: Allowed URIs list, space separated
        required: true
        type: array
        items: string
        collectionFormat: ssv
    name:
      required:
        in: formData
        name: name
        description: A unique name for your client
        required: true
        type: string

################################################################################
#                                    Paths                                     #
################################################################################


paths:
  /clients:
    post:
      operationId: registerClient
      summary: Register an OAuth client
      description: Registers your OAuth client with the InterSIS instance.
      tags:
        - clients
      parameters:
        - $ref: '#/parameters/clients/redirect_uris/required'
        - $ref: '#/parameters/clients/name/required'
      responses:
        200:
          description: OK - The client object
          schema:
            $ref: '#/definitions/Client'
        403:
          description: Forbidden - The server does not allow automated client registration.
  /whoami:
    get:
      operationId: identifyUser
      tags:
        - whoami
      summary: Get identifying user information
      description: |
        Get the user ID associated with a provided token, as well as any staff, student or guardian associated with
        the user.
      security:
        - oauth:
          - read-client
      responses:
        200:
          description: OK - User details
          schema:
            properties:
              id:
                type: string
                example: t6y4zo26vutj4xclh5hpy3sc5m


################################################################################
#                                 Definitions                                  #
################################################################################
definitions:
  # Models
  Client:
    description: The client accessing the API
    type: object
    required:
      - id
      - name
      - redirect_uris
    properties:
      id:
        type: string
        example: t6y4zo26vutj4xclh5hpy3sc5m
      redirect_uris:
        type: array
        items:
          type: string
      client_type:
        type: string
      authorization_grant_type:
        type: string
      client_secret:
        type: string
      name:
        type: string
  Reference:
    type: object
    properties:
      uri:
        type: string
        example: /api/objects/t6y4zo26vutj4xclh5hpy3sc5m
  UnrecognizedID:
    required:
      - error
    properties:
      error:
        type: object
        required:
          - httpStatus
          - requestedID
          - dateTime
        properties:
          httpStatus:
            type: integer
            description: 404 for unrecognizedID
            example: 404
          dateTime:
            type: string
            description: ISO format timestamp of the request
            example: 2015-09-14T09:45:19+00:00
          requestedID:
            type: string
            description: The ID not recognized
            example: t6y4zo26vutj4xclh5hpy3sc5m
          errorMessage:
            type: string
            description: (if provided) additional error information
            example: ID not found
  Error:
    required:
      - error
    properties:
      error:
        type: object
        required:
          - httpStatus
          - dateTime
        properties:
          httpStatus:
            type: integer
            description: http status code of bad request
            example: 501
          dateTime:
            type: string
            description: ISO format timestamp of the request
            example: 2015-09-14T09:14:30+00:00
          requestParameters:
            type: array
            description: parameters of the bad request
            items:
              type: array
              items:
                type: string
            example: '[[param1, 12345], [param2, 12354]]'
          errorMessage:
            type: string
            description: (if provided) additional error information
            example: Bad request
  
